IF NOT EXISTS (SELECT * FROM dbo.UserRole WHERE Id = 1)
INSERT INTO dbo.UserRole values (1, 'Developer')
IF NOT EXISTS (SELECT * FROM dbo.UserRole WHERE [Id] = 2)
INSERT INTO dbo.UserRole values (2, 'QA')
IF NOT EXISTS (SELECT * FROM dbo.UserRole WHERE [Id] = 3)
INSERT INTO dbo.UserRole values (3, 'Manager')

IF NOT EXISTS (SELECT * FROM dbo.IssueType WHERE [Id] = 1)
INSERT INTO IssueTypes values (1, 'Bug')
IF NOT EXISTS (SELECT * FROM dbo.IssueType WHERE [Id] = 2)
INSERT INTO IssueTypes values (2, 'Task')
IF NOT EXISTS (SELECT * FROM dbo.IssueType WHERE [Id] = 3)
INSERT INTO IssueTypes values (3, 'Feature')

IF NOT EXISTS (SELECT * FROM dbo.IssueStatus WHERE [Id] = 1)
INSERT INTO IssueStatus values (1, 'Submitted')
IF NOT EXISTS (SELECT * FROM dbo.IssueStatus WHERE [Id] = 2)
INSERT INTO IssueStatus values (2, 'Open')
IF NOT EXISTS (SELECT * FROM dbo.IssueStatus WHERE [Id] = 3)
INSERT INTO IssueStatus values (3, 'Closed')
IF NOT EXISTS (SELECT * FROM dbo.IssueStatus WHERE [Id] = 4)
INSERT INTO IssueStatus values (4, 'Re-Opened')

IF NOT EXISTS (SELECT * FROM dbo.IssuePriority WHERE [Id] = 1)
INSERT INTO IssuePriorities values (1, 'Low')
IF NOT EXISTS (SELECT * FROM dbo.IssuePriority WHERE [Id] = 2)
INSERT INTO IssuePriorities values (2, 'Medium')
IF NOT EXISTS (SELECT * FROM dbo.IssuePriority WHERE [Id] = 3)
INSERT INTO IssuePriorities values (3, 'High')
IF NOT EXISTS (SELECT * FROM dbo.IssuePriority WHERE [Id] = 4)
INSERT INTO IssuePriorities values (4, 'Critical')
